import { useState } from "react";
import { Code } from "lucide-react";

export default function CodeViewerPage() {
  const [selectedFile, setSelectedFile] = useState<string | null>(null);

  return (
    <div className="page">
      <h1><Code size={24} /> Code Viewer</h1>
      <div className="code-viewer-layout">
        <div className="code-sidebar">
          <h3>Generated Files</h3>
          <p className="muted">
            Code files generated by agents will appear here once a mission is executing.
          </p>
          <div className="file-tree">
            <div className="file-tree-item" onClick={() => setSelectedFile("README.md")}>
              README.md
            </div>
            <div className="file-tree-item" onClick={() => setSelectedFile("architecture.md")}>
              /shared/architecture.md
            </div>
          </div>
        </div>
        <div className="code-content">
          {selectedFile ? (
            <div className="code-block">
              <div className="code-header">{selectedFile}</div>
              <pre>
                <code>
                  {`# Code viewer\n\nThis page will display agent-generated code once the mission is running.\nFiles are tracked in the git repository created for each mission.`}
                </code>
              </pre>
            </div>
          ) : (
            <div className="empty-state">
              <Code size={48} />
              <p>Select a file from the sidebar to view its contents.</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
